Fix: Change getData() to getFormDataAsObject() in validate method
CheckRegisterForm.validate() was calling this.getData() which doesn't exist.
FormHandler provides getFormDataAsObject() method instead.

This fixes the error: 'this.getData is not a function' when submitting entries.